[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Kaia Chain Configuration
[profile.kaia]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
#nodit service(https://nodit.lambda256.io/projects/1755670145066626540/overview?tab=dashboard&node=1755670145191737576)
kaia_mainnet = "https://kaia-mainnet.nodit.io/${NODIT_API_KEY}"
kaia_testnet = "https://kaia-kairos.nodit.io/${NODIT_API_KEY}"

[etherscan]
kaia_mainnet = { key = "${KAIASCAN_API_KEY}", url = "https://mainnet-oapi.kaiascan.io/api" }
kaia_testnet = { key = "${KAIASCAN_API_KEY}", url = "https://kairos-oapi.kaiascan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
